require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'demo_project' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'demo_projectTests' do
    inherit! :complete
    # Pods for testing
  end

end

target 'demo_project-tvOS' do
  # Pods for demo_project-tvOS

  target 'demo_project-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
